management:
  endpoint:
    health:
      messageCheckEnvEnabled: ${MESSAGE_HEALTH_CHECK_ENV:prod,aat}
      environment: ${ENVIRONMENT:local}
      allowedStalePeriod: ${ALLOWED_STALE_PERIOD:5}
      show-details: "always"
      show-components: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, messagePublisherLiveness
        readiness:
          include: readinessState
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
    jolokia:
      sensitive: false

hawtio:
  authenticationEnabled: false

spring:
  jms:
    servicebus:
      enabled: false
  activemq:
    in-memory: true
    broker-url: vm://localhost?broker.persistent=false
  autoconfigure:
    exclude:
