spring:
  jms:
    servicebus:
      enabled: false
  activemq:
    in-memory: true
    broker-url: vm://localhost?broker.persistent=false
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:9.6:///databasename?TC_INITSCRIPT=sql/init-db.sql
  autoconfigure:
    exclude:

message-publisher:
  tasks:
