spring:
  jms:
    servicebus:
      enabled: false
  activemq:
    in-memory: true
    broker-url: vm://localhost?broker.persistent=false
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:9.6:///databasename?TC_INITSCRIPT=sql/init-db.sql
  autoconfigure:
    exclude:

message-publisher:
  tasks:

management:
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    ssl:
      enabled: false
  endpoint:
    health:
      messageCheckEnvEnabled: ${MESSAGE_HEALTH_CHECK_ENV:test}
      environment: ${ENVIRONMENT:test}
      allowedStalePeriod: ${ALLOWED_STALE_PERIOD:5}
      show-details: "always"
      show-components: always
      group:
        liveness:
          include: livenessState, messagePublisherLiveness
        readiness:
          include: readinessState
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
